
title="config"

[app]
    page_size=10



[server]
    port=8080
    read_timeout=60
    write_timeout=60


[mysql]
    user="root"
    password="1234"
    host="localhost:3306"
    name="file-store"

[redis]
    host="localhost:6379"
    index="1"

#qq互联中注册id
[qq]
    app_id="111"
    redirect_url="http://www.pyxgo.cn/callbackQQ"
    app_key="22"

[oss]
    access_key_id=""
    access_key_secret=""
    end_point=""
    bucket_name=""


